version: '3.7'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14
    restart: always
    env_file:
      - ../../.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
